#version: "2.0"

networks:
  laravel:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./src:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./src:/code
    networks:
      - laravel

  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    # - MYSQL_DATABASE=semar_coding
    # - MYSQL_USER=semar
    # - MYSQL_PASSWORD=semar
    ports:
      - 3306:3306
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel
